[package]
name = "redshiftzero-pazk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "0.3"
ark-bls12-377 = "0.3"
rand_core = { version = "0.6.3", features = ["getrandom"] }
